name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  run-deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install dependiencies
        run: npm install --froxen-lockfile
      - name: Build the app
        run: npm run Build
      - name: Check files
        run: ls -al
      - name: Deploy to Github Pages
        uese: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
